version: 2.1
workflows:
  main:
    jobs: ['linux-arm64', 'ios']

jobs:
  # linux/arm64
  linux-arm64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install-go
          command: |
            sudo apt -y install golang

      - run:
          name: test
          command: 'go test ./...'

  # iOS
  ios:
    macos:
      xcode: 13.4.1
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install-go
          command: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew install go

      - run:
          name: test
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests
          command: |
            export PATH=$PATH:/usr/local/Cellar/go/*/bin
            go test ./...
