name: 'build'
on:
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/*']
  push:
    branches: ['master']

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        go: ['1.18', '1.22']
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-go@v5'
        with:
          go-version: ${{ matrix.go }}

      - name: build
        run: |
          for a in $(go tool dist list); do
            export GOOS=${a%%/*}
            export GOARCH=${a#*/}

            case "$GOOS" in
              (android|ios)  exit 0 ;; # Doesn't cross-compile.
            esac

            go test -c
          done
