name: 'test'
on:
  pull_request:
    paths: ['**.go', 'go.mod', '.github/workflows/*']
  push:
    branches: ['master']

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-latest']
        go: ['1.18', '1.22']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v5'
        with:
          go-version: '${{ matrix.go }}'
      - name: 'test'
        run: 'go test -race ./...'

  windows:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        go: ['1.18', '1.22']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v5'
        with:
          go-version: '${{ matrix.go }}'
      - name: 'test'
        run: 'go test -race ./...'

  macos:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'macos-latest']
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v5'
        with:
          go-version: '1.22'
      - name: 'test'
        run: 'go test ./...'

  openbsd:
    runs-on: 'ubuntu-latest'
    name: 'test (openbsd, 1.17)'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (openbsd, 1.17)'
        id:   'openbsd'
        uses: 'vmactions/openbsd-vm@v1'
        with:
          prepare: 'pkg_add go'
          run: 'go test ./...'

  netbsd:
    runs-on: 'ubuntu-latest'
    name: 'test (netbsd, 1.21)'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (netbsd, 1.21)'
        id:   'netbsd'
        uses: 'vmactions/netbsd-vm@v1'
        with:
          prepare: 'pkg_add go'
          run: 'go test ./...'

  # DragonFlyBSD
  dragonflybsd:
    runs-on: 'ubuntu-latest'
    name: 'test (dragonflybsd, 1.20)'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'test (dragonflybsd, 1.20)'
        id:   'dragonflybsd'
        uses: 'vmactions/dragonflybsd-vm@v1'
        with:
          prepare: 'pkg install -y go'
          run: 'go test ./...'

  # illumos
  illumos:
    runs-on: 'ubuntu-latest'
    name: 'test (illumos, 1.22)'
    steps:
    - uses: 'actions/checkout@v4'
    - name: 'test (illumos, 1.22)'
      id:   'illumos'
      uses: 'vmactions/omnios-vm@v1'
      with:
        prepare: 'pkg install go-122'
        run: |
          export GOCACHE=/tmp/go-cache
          export GOPATH=/tmp/go-path
          go test ./...
